
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/mingw64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:13 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Windows - 6.2.9200 - 
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/mingw64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/mingw64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/mingw64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: c:/Program Files/Microchip/xc16/v2.10/bin/xc16-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Assembler messages:
      Warning: Using default target divide cycle count of 17; please specify device.
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        F:/Projects_Embedded/Fashionable-Watch/_build/LabC7_I2C_Accel/default/CMakeFiles/3.28.1/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/mingw64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "C:/Program Files/mingw64/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      elf-gcc.exe (Microchip Technology) 4.5.1 (XC16, Microchip v2.10)  (A) Build date: Mar 27 2023
      Part support version: 2.10 (A)
      __XC16_VERSION__ == 2010
      Copyright (C) 2010 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
...
