#ifndef OLEDC_C_COLORS_H
#define OLEDC_C_COLORS_H

#include <stdint.h>

#define OLEDC_COLOR_ALICEBLUE          0xf7df
#define OLEDC_COLOR_ANTIQUEWHITE       0xff5a
#define OLEDC_COLOR_AQUA               0x7ff
#define OLEDC_COLOR_AQUAMARINE         0x7ffa
#define OLEDC_COLOR_AZURE              0xf7ff
#define OLEDC_COLOR_BEIGE              0xf7bb
#define OLEDC_COLOR_BISQUE             0xff38
#define OLEDC_COLOR_BLACK              0x0
#define OLEDC_COLOR_BLANCHEDALMOND     0xff59
#define OLEDC_COLOR_BLUE               0x1f
#define OLEDC_COLOR_BLUEVIOLET         0x895c
#define OLEDC_COLOR_BROWN              0xa145
#define OLEDC_COLOR_BURLYWOOD          0xddd0
#define OLEDC_COLOR_CADETBLUE          0x5cf4
#define OLEDC_COLOR_CHARTREUSE         0x7fe0
#define OLEDC_COLOR_CHOCOLATE          0xd343
#define OLEDC_COLOR_CORAL              0xfbea
#define OLEDC_COLOR_CORNFLOWERBLUE     0x64bd
#define OLEDC_COLOR_CORNSILK           0xffdb
#define OLEDC_COLOR_CRIMSON            0xd8a7
#define OLEDC_COLOR_CYAN               0x7ff
#define OLEDC_COLOR_DARKBLUE           0x11
#define OLEDC_COLOR_DARKCYAN           0x451
#define OLEDC_COLOR_DARKGOLDENROD      0xbc21
#define OLEDC_COLOR_DARKGRAY           0xad55
#define OLEDC_COLOR_DARKGREEN          0x320
#define OLEDC_COLOR_DARKGREY           0xad55
#define OLEDC_COLOR_DARKKHAKI          0xbdad
#define OLEDC_COLOR_DARKMAGENTA        0x8811
#define OLEDC_COLOR_DARKOLIVEGREEN     0x5345
#define OLEDC_COLOR_DARKORANGE         0xfc60
#define OLEDC_COLOR_DARKORCHID         0x9999
#define OLEDC_COLOR_DARKRED            0x8800
#define OLEDC_COLOR_DARKSALMON         0xecaf
#define OLEDC_COLOR_DARKSEAGREEN       0x8df1
#define OLEDC_COLOR_DARKSLATEBLUE      0x49f1
#define OLEDC_COLOR_DARKSLATEGRAY      0x2a69
#define OLEDC_COLOR_DARKSLATEGREY      0x2a69
#define OLEDC_COLOR_DARKTURQUOISE      0x67a
#define OLEDC_COLOR_DARKVIOLET         0x901a
#define OLEDC_COLOR_DEEPPINK           0xf8b2
#define OLEDC_COLOR_DEEPSKYBLUE        0x5ff
#define OLEDC_COLOR_DIMGRAY            0x6b4d
#define OLEDC_COLOR_DIMGREY            0x6b4d
#define OLEDC_COLOR_DODGERBLUE         0x1c9f
#define OLEDC_COLOR_FIREBRICK          0xb104
#define OLEDC_COLOR_FLORALWHITE        0xffde
#define OLEDC_COLOR_FORESTGREEN        0x2444
#define OLEDC_COLOR_FUCHSIA            0xf81f
#define OLEDC_COLOR_GAINSBORO          0xdefb
#define OLEDC_COLOR_GHOSTWHITE         0xffdf
#define OLEDC_COLOR_GOLD               0xfea0
#define OLEDC_COLOR_GOLDENROD          0xdd24
#define OLEDC_COLOR_GRAY               0x8410
#define OLEDC_COLOR_GREEN              0x400
#define OLEDC_COLOR_GREENYELLOW        0xafe5
#define OLEDC_COLOR_GREY               0x8410
#define OLEDC_COLOR_HONEYDEW           0xf7fe
#define OLEDC_COLOR_HOTPINK            0xfb56
#define OLEDC_COLOR_INDIANRED          0xcaeb
#define OLEDC_COLOR_INDIGO             0x4810
#define OLEDC_COLOR_IVORY              0xfffe
#define OLEDC_COLOR_KHAKI              0xf731
#define OLEDC_COLOR_LAVENDER           0xe73f
#define OLEDC_COLOR_LAVENDERBLUSH      0xff9e
#define OLEDC_COLOR_LAWNGREEN          0x7fe0
#define OLEDC_COLOR_LEMONCHIFFON       0xffd9
#define OLEDC_COLOR_LIGHTBLUE          0xaedc
#define OLEDC_COLOR_LIGHTCORAL         0xf410
#define OLEDC_COLOR_LIGHTCYAN          0xe7ff
#define OLEDC_COLOR_LIGHTGOLDENRODYELLOW 0xffda
#define OLEDC_COLOR_LIGHTGRAY          0xd69a
#define OLEDC_COLOR_LIGHTGREEN         0x9772
#define OLEDC_COLOR_LIGHTGREY          0xd69a
#define OLEDC_COLOR_LIGHTPINK          0xfdb8
#define OLEDC_COLOR_LIGHTSALMON        0xfd0f
#define OLEDC_COLOR_LIGHTSEAGREEN       0x2595
#define OLEDC_COLOR_LIGHTSKYBLUE       0x867f
#define OLEDC_COLOR_LIGHTSLATEGRAY      0x7453
#define OLEDC_COLOR_LIGHTSLATEGREY      0x7453
#define OLEDC_COLOR_LIGHTSTEELBLUE     0xb63b
#define OLEDC_COLOR_LIGHTYELLOW        0xfffc
#define OLEDC_COLOR_LIME               0x7e0
#define OLEDC_COLOR_LIMEGREEN          0x3666
#define OLEDC_COLOR_LINEN              0xff9c
#define OLEDC_COLOR_MAGENTA            0xf81f
#define OLEDC_COLOR_MAROON             0x8000
#define OLEDC_COLOR_MEDIUMAQUAMARINE   0x6675
#define OLEDC_COLOR_MEDIUMBLUE         0x19
#define OLEDC_COLOR_MEDIUMORCHID       0xbaba
#define OLEDC_COLOR_MEDIUMPURPLE       0x939b
#define OLEDC_COLOR_MEDIUMSEAGREEN     0x3d8e
#define OLEDC_COLOR_MEDIUMSLATEBLUE    0x7b5d
#define OLEDC_COLOR_MEDIUMSPRINGGREEN  0x7d3
#define OLEDC_COLOR_MEDIUMTURQUOISE    0x4e99
#define OLEDC_COLOR_MEDIUMVIOLETRED    0xc0b0
#define OLEDC_COLOR_MIDNIGHTBLUE       0x18ce
#define OLEDC_COLOR_MINTCREAM          0xf7ff
#define OLEDC_COLOR_MISTYROSE          0xff3c
#define OLEDC_COLOR_MOCCASIN           0xff36
#define OLEDC_COLOR_NAVAJOWHITE        0xfef5
#define OLEDC_COLOR_NAVY               0x10
#define OLEDC_COLOR_OLDLACE            0xffbc
#define OLEDC_COLOR_OLIVE              0x8400
#define OLEDC_COLOR_OLIVEDRAB          0x6c64
#define OLEDC_COLOR_ORANGE             0xfd20
#define OLEDC_COLOR_ORANGERED          0xfa20
#define OLEDC_COLOR_ORCHID             0xdb9a
#define OLEDC_COLOR_PALEGOLDENROD      0xef55
#define OLEDC_COLOR_PALEGREEN          0x9fd3
#define OLEDC_COLOR_PALETURQUOISE      0xaf7d
#define OLEDC_COLOR_PALEVIOLETRED      0xdb92
#define OLEDC_COLOR_PAPAYAWHIP         0xff7a
#define OLEDC_COLOR_PEACHPUFF          0xfed7
#define OLEDC_COLOR_PERU               0xcc27
#define OLEDC_COLOR_PINK               0xfe19
#define OLEDC_COLOR_PLUM               0xdd1b
#define OLEDC_COLOR_POWDERBLUE         0xb71c
#define OLEDC_COLOR_PURPLE             0x8010
#define OLEDC_COLOR_RED                0xf800
#define OLEDC_COLOR_ROSYBROWN          0xbc71
#define OLEDC_COLOR_ROYALBLUE          0x435c
#define OLEDC_COLOR_SADDLEBROWN        0x8a22
#define OLEDC_COLOR_SALMON             0xfc0e
#define OLEDC_COLOR_SANDYBROWN         0xf52c
#define OLEDC_COLOR_SEAGREEN           0x2c4a
#define OLEDC_COLOR_SEASHELL           0xffbd
#define OLEDC_COLOR_SIENNA             0xa285
#define OLEDC_COLOR_SILVER             0xc618
#define OLEDC_COLOR_SKYBLUE            0x867d
#define OLEDC_COLOR_SLATEBLUE          0x6ad9
#define OLEDC_COLOR_SLATEGRAY          0x7412
#define OLEDC_COLOR_SLATEGREY          0x7412
#define OLEDC_COLOR_SNOW               0xffdf
#define OLEDC_COLOR_SPRINGGREEN        0x7ef
#define OLEDC_COLOR_STEELBLUE          0x4416
#define OLEDC_COLOR_TAN                0xd5b1
#define OLEDC_COLOR_TEAL               0x410
#define OLEDC_COLOR_THISTLE            0xddfb
#define OLEDC_COLOR_TOMATO             0xfb08
#define OLEDC_COLOR_TURQUOISE          0x471a
#define OLEDC_COLOR_VIOLET             0xec1d
#define OLEDC_COLOR_WHEAT              0xf6f6
#define OLEDC_COLOR_WHITE              0xffff
#define OLEDC_COLOR_WHITESMOKE         0xf7be
#define OLEDC_COLOR_YELLOW             0xffe0
#define OLEDC_COLOR_YELLOWGREEN        0x9e66

#endif	/* OLEDC_C_COLORS_H */